import { PageSearchResult, PageOverview, Post } from '@/types';

export const MOCK_PAGES: PageSearchResult[] = [
  {
    id: '107418956303655',
    name: 'NASA',
    category: 'Science & Technology',
    fanCount: 21400000,
    pictureUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/192px-NASA_logo.svg.png',
  },
  {
    id: '16547831471',
    name: 'NASA Jet Propulsion Laboratory',
    category: 'Science & Technology',
    fanCount: 3100000,
    pictureUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/JPL_logo.svg/192px-JPL_logo.svg.png',
  },
  {
    id: '54212720926',
    name: 'NASA Earth',
    category: 'Organisation',
    fanCount: 800000,
    pictureUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/The_Earth_seen_from_Apollo_17.jpg/192px-The_Earth_seen_from_Apollo_17.jpg',
  },
  {
    id: '1419681648293905',
    name: 'BBC News',
    category: 'News & Media',
    fanCount: 50000000,
    pictureUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/BBC_News_2019.svg/192px-BBC_News_2019.svg.png',
  },
  {
    id: '200040983411486',
    name: 'National Geographic',
    category: 'Magazine',
    fanCount: 47000000,
    pictureUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Natgeo_rectangle.svg/192px-Natgeo_rectangle.svg.png',
  },
  {
    id: '8304333127',
    name: 'Harvard University',
    category: 'University',
    fanCount: 8200000,
    pictureUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/29/Harvard_shield_wreath.svg/192px-Harvard_shield_wreath.svg.png',
  },
];

export const MOCK_PAGE_OVERVIEW: PageOverview = {
  id: '107418956303655',
  name: 'NASA',
  category: 'Science & Technology',
  fanCount: 21400000,
  about: 'Explore the universe and discover our home planet with NASA. We usually post updates 4–5 times per week.',
  website: 'https://www.nasa.gov',
  pictureUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/192px-NASA_logo.svg.png',
  coverUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Earth_from_Space.jpg/1200px-Earth_from_Space.jpg',
  metrics: {
    fanCount: 21400000,
    totalPosts: 25,
    avgReactions: 4820,
    avgShares: 1230,
    avgComments: 342,
    engagementRate: 0.029,
  },
};

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();

export const MOCK_POSTS: Post[] = [
  {
    id: 'post_001',
    message: 'Stunning new images from the James Webb Space Telescope show galaxies forming just 300 million years after the Big Bang. These images reshape our understanding of the early universe and push the boundaries of what we thought was possible.',
    createdTime: daysAgo(7),
    type: 'photo',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/HST-SM4.jpeg/800px-HST-SM4.jpeg',
    reactions: 48200,
    shares: 12100,
    comments: 3400,
    viralityScore: 9.2,
    engagementBarPercent: 92,
  },
  {
    id: 'post_002',
    message: 'NASA\'s Artemis program marks a new era of lunar exploration. Watch live as we prepare to return humans to the Moon for the first time in over 50 years. This mission will pave the way for future crewed missions to Mars.',
    createdTime: daysAgo(14),
    type: 'video',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/NASA_logo.svg/800px-NASA_logo.svg.png',
    reactions: 35600,
    shares: 8900,
    comments: 2100,
    viralityScore: 7.8,
    engagementBarPercent: 78,
  },
  {
    id: 'post_003',
    message: 'Earth as seen from the International Space Station. Our planet is breathtakingly beautiful — and worth protecting. Today is Earth Day, a reminder to care for the only home we\'ve ever known.',
    createdTime: daysAgo(21),
    type: 'photo',
    thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/The_Earth_seen_from_Apollo_17.jpg/800px-The_Earth_seen_from_Apollo_17.jpg',
    reactions: 52100,
    shares: 14300,
    comments: 1800,
    viralityScore: 8.9,
    engagementBarPercent: 89,
  },
  {
    id: 'post_004',
    message: 'Meet Ingenuity — the first aircraft to achieve powered, controlled flight on another planet. Mars helicopter has now completed 72 flights and continues to push boundaries far beyond its original mission parameters.',
    createdTime: daysAgo(28),
    type: 'photo',
    thumbnailUrl: null,
    reactions: 28400,
    shares: 6700,
    comments: 1500,
    viralityScore: 6.5,
    engagementBarPercent: 65,
  },
  {
    id: 'post_005',
    message: 'Did you know? The Sun produces about 386 billion megawatts of energy every second. Our star is a dynamic, ever-changing system that influences everything in our solar system. Share this with someone who loves space!',
    createdTime: daysAgo(35),
    type: 'status',
    thumbnailUrl: null,
    reactions: 15200,
    shares: 3400,
    comments: 890,
    viralityScore: 4.2,
    engagementBarPercent: 42,
  },
  {
    id: 'post_006',
    message: 'SpaceX and NASA successfully dock the Crew Dragon with the International Space Station. Four astronauts are now aboard the ISS for a six-month science mission. This marks the 10th crewed Commercial Crew mission.',
    createdTime: daysAgo(42),
    type: 'video',
    thumbnailUrl: null,
    reactions: 31800,
    shares: 7200,
    comments: 2300,
    viralityScore: 7.1,
    engagementBarPercent: 71,
  },
  {
    id: 'post_007',
    message: 'Black hole at the centre of our galaxy photographed for the first time. Sagittarius A* is 4 million times the mass of our Sun, located 26,000 light-years from Earth. The Event Horizon Telescope team made history today.',
    createdTime: daysAgo(49),
    type: 'link',
    thumbnailUrl: null,
    reactions: 44700,
    shares: 11500,
    comments: 4200,
    viralityScore: 9.0,
    engagementBarPercent: 90,
  },
  {
    id: 'post_008',
    message: 'Mars Global Surveyor captures new dust storm forming on the red planet. Scientists monitor these planetary-scale weather events to better understand Martian climate and plan future human missions.',
    createdTime: daysAgo(56),
    type: 'photo',
    thumbnailUrl: null,
    reactions: 12300,
    shares: 2800,
    comments: 670,
    viralityScore: 3.4,
    engagementBarPercent: 34,
  },
  {
    id: 'post_009',
    message: 'NASA celebrates 25 years of the Hubble Space Telescope. Over a quarter century of discovery — from nearby nebulae to the edges of the observable universe. Hubble has transformed our understanding of the cosmos.',
    createdTime: daysAgo(63),
    type: 'photo',
    thumbnailUrl: null,
    reactions: 38900,
    shares: 9400,
    comments: 2800,
    viralityScore: 8.1,
    engagementBarPercent: 81,
  },
  {
    id: 'post_010',
    message: 'Scientists discover water ice deposits near the lunar south pole. This finding has major implications for future human habitation of the Moon — water means breathable air, drinking water, and even rocket fuel.',
    createdTime: daysAgo(70),
    type: 'link',
    thumbnailUrl: null,
    reactions: 21600,
    shares: 5100,
    comments: 1340,
    viralityScore: 5.8,
    engagementBarPercent: 58,
  },
  {
    id: 'post_011',
    message: 'OSIRIS-REx successfully delivers asteroid samples from Bennu to Earth. These pristine materials from the early solar system could reveal the origins of life. The capsule landed safely in Utah desert.',
    createdTime: daysAgo(77),
    type: 'video',
    thumbnailUrl: null,
    reactions: 41200,
    shares: 10800,
    comments: 3100,
    viralityScore: 8.7,
    engagementBarPercent: 87,
  },
  {
    id: 'post_012',
    message: 'New exoplanet discovered in the habitable zone of its star. TRAPPIST-1e shows signs of a rocky surface and liquid water. This brings us one step closer to answering humanity\'s oldest question: are we alone?',
    createdTime: daysAgo(84),
    type: 'status',
    thumbnailUrl: null,
    reactions: 33400,
    shares: 8600,
    comments: 5700,
    viralityScore: 8.4,
    engagementBarPercent: 84,
  },
];
